### ISSUE TITLE
Does it support tokens to id?

### ISSUE THREAD

**Issue by raj-shah14** [microsoft/BlingFire#51]
I have lists of list, and each list contains word token and is of different length. Is there a function token_to_ids like text_to_ids? 
Bert tokenizer has similar function like "convert_tokens_to_ids".

**Comment by raj-shah14** [comment]
https://github.com/microsoft/BlingFire/issues/52#issuecomment-615426106

**Comment by smbecker** [comment]
Unfortunately, `TextToIds` doesn't seem to always work. I am using the xlnet model and running `TextToIds('<sep>')` returns `[17, 4]`. Sure, I could just dump the first token and only respect the `4`, which is the correct answer. However, running `TextToIds('<unk>')` returns `[7739, 12287, 3151]`, which isn't even close to accurate since `<unk>=0`. A proper `TokenToId` function would be really useful. Are you open to accepting PRs?
