### ISSUE TITLE
Feature Request: ids_to_text method

### ISSUE THREAD

**Issue by ankane** [microsoft/BlingFire#83]
Hi, it'd be nice if there was a method to convert ids to text. This would allow Bling Fire to used with text generation models. Here's similar code from Hugging Face's Transformers:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
print(tokenizer.decode([1188, 1110, 170, 2774])) # prints "This is a test"
```

**Comment by SergeiAlonichau** [comment]
Hmm... for generation it makes sense. I did not want to add it initially because model still may encounter UNK tokens, in this case reconstruction of a string from a sequence of ids is not possible (because of UNKs). I guess a generation model should never generate an UNK so reconstruction should be possible... Ok, let me add it.

**Comment by shlomimaliah** [comment]
Is there any update about this request?

**Comment by SergeiAlonichau** [comment]
Done in 0.1.8 release

**Comment by SergeiAlonichau** [comment]
Here is an example code: https://github.com/microsoft/BlingFire/blob/master/scripts/blingfire_example.py

**Comment by ankane** [comment]
Big thanks @SergeiAlonichau, this is really great! 🎉  Added it to the Ruby library, and going to try it out with text generation models.
