### ISSUE TITLE
HuggingFace export

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/BlingFire#91]
For .NET developer, when attempting to convert HuggingFace transformer models to ONNX, we lack the .NET version of tokenizers provided by the HuggingFace transformers framework.

To promote ONNX adoption for .NET developer, please provide or if better the .NET version for various tokenizers used in the HuggingFace transformers

e.g. is it possible to have [**BertTokenizer**](https://www.nuget.org/packages/BertTokenizer/) class with similar functions and semantic ussage to the HuggingFace transformer **BertTokenizerFast** shown below

![image](https://user-images.githubusercontent.com/49812372/107159728-33322c80-6992-11eb-88a7-6e68735a409e.png)

**Comment by SergeiAlonichau** [comment]
Our C++ APIs allow to get IDs, offsets and certain type of preprocessing, so I am pretty sure you can create tokens dictionary you have here with a few lines of code already. 

On the other hand if you want a tight integration with Huggingface models, you can create a BertTokenizerBlingFire class which under the hood uses our APIs but otherwise has an interface of a Huggingface tokenizer.
